# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(choices=[('tuberculosis', 'tuberculosis'), ('AIDS', 'AIDS'), ('malaria', 'malaria')], max_length=16),
        ),
    ]
